SET search_path TO application_db;

ALTER TABLE T_TEAM ADD CONSTRAINT DEFAULT_LOCATION CHECK(DEFAULT_LOCATION IN ('LISBON', 'BRAGA', 'PORTO'));

ALTER TABLE T_TEAM_MEMBER ADD CONSTRAINT FK_T_TEAM FOREIGN KEY (TEAM_ID) REFERENCES T_TEAM(ID);

ALTER TABLE T_RACK
    ADD CONSTRAINT STATUS CHECK(STATUS IN ('ACTIVE', 'RETURNED', 'REPAIR', 'OUTDATED', 'BRICKED')),
    ADD CONSTRAINT DEFAULT_LOCATION CHECK(DEFAULT_LOCATION IN ('LISBON', 'BRAGA', 'PORTO')),
    ADD CONSTRAINT FK_T_TEAM_R FOREIGN KEY (TEAM_ID) REFERENCES T_TEAM(id);

ALTER TABLE T_RACK_ASSET ADD FOREIGN KEY (RACK_ID) REFERENCES T_RACK(ID);

ALTER TABLE T_BOOKING
    ADD CONSTRAINT FK_T_TEAM_MEMBER FOREIGN KEY (REQUESTER_ID) REFERENCES T_TEAM_MEMBER(ID),
    ADD CONSTRAINT FK_RACK FOREIGN KEY (RACK_ID) REFERENCES T_RACK(ID);