name: Build
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  path_dockerfile:
    description: 'Path to the Dockerfile'
    required: true
    default: "./src/main/docker/Dockerfile.jvm"
  image_name:
    description: 'Name of the Docker image to be built'
    required: false
    default: "academy"
  tag_name:
    description: 'Tag for the Docker image'
    required: true
    default: ""
runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set image
      run: |
            if [ -z "${{inputs.tag_name}}" ]; then
              echo "TAG=$(date +%s)" >> $GITHUB_ENV
            else
              echo "TAG=${{inputs.tag_name}}" >> $GITHUB_ENV
            fi
            echo "DOCKER_IMAGE_NAME=${{inputs.image_name}}" >> $GITHUB_ENV
      shell: bash

    - name: Build docker image
      shell: bash
      run: |
            echo "${{inputs.path_dockerfile}}"
            docker build . --file ${{inputs.path_dockerfile }} --tag $DOCKER_IMAGE_NAME:$TAG

    - name: List docker images
      shell: bash
      run: docker image ls

    - name: Push to docker hub
      shell: bash
      run: |
            docker tag $DOCKER_IMAGE_NAME:$TAG cicdrepo:$TAG
            docker push cicdrepo:$TAG

    - name: list
      shell: bash
      run: ls